ICONS = (
	('camera', 'Camera'),
    ('building-o', 'Building'),
    ('align-left', 'Align left'),
    ('hand-o-up', 'Handup'),
    ('external-link-square', 'External link square'),
    ('comment-o', 'Comment'),
    ('thumbs-o-down', 'Thumbsdown'),
    ('heart', 'Heart'),
    ('list', 'List'),
    ('euro', 'Euro'),
    ('stethoscope', 'Stethoscope'),
    ('bookmark', 'Bookmark'),
    ('barcode', 'Barcode'),
    ('th-large', 'TH large'),
    ('square', 'Square'),
    ('times-circle-o', 'Times circle'),
    ('tachometer', 'Tachometer'),
    ('bell-o', 'Bell'),
    ('leaf', 'Leaf'),
    ('skype', 'Skype'),
    ('certificate', 'Certificate'),
    ('arrows-alt', 'Arrows alt'),
    ('subscript', 'Subscript'),
    ('road', 'Road'),
    ('times-circle', 'Times circle'),
    ('list-ul', 'List ul'),
    ('arrow-circle-o-down', 'Arrow circledown'),
    ('check-circle', 'Check circle'),
    ('chevron-circle-up', 'Chevron circle up'),
    ('circle', 'Circle'),
    ('gbp', 'GBP'),
    ('umbrella', 'Umbrella'),
    ('sort-numeric-asc', 'Sort numeric asc'),
    ('pencil-square', 'Pencil square'),
    ('trash-o', 'Trash'),
    ('share-square-o', 'Share square'),
    ('users', 'Users'),
    ('yen', 'Yen'),
    ('unlink', 'Unlink'),
    ('ban', 'Ban'),
    ('film', 'Film'),
    ('folder-o', 'Folder'),
    ('file-text', 'File text'),
    ('list-alt', 'List alt'),
    ('th-list', 'TH list'),
    ('filter', 'Filter'),
    ('caret-up', 'Caret up'),
    ('sign-out', 'Sign out'),
    ('pencil', 'Pencil'),
    ('ticket', 'Ticket'),
    ('hand-o-left', 'Handleft'),
    ('html5', 'Html5'),
    ('dropbox', 'Dropbox'),
    ('long-arrow-up', 'Long arrow up'),
    ('stack-overflow', 'Stack overflow'),
    ('chevron-circle-left', 'Chevron circle left'),
    ('check-square', 'Check square'),
    ('cloud-download', 'Cloud download'),
    ('caret-square-o-down', 'Caret squaredown'),
    ('microphone-slash', 'Microphone slash'),
    ('folder', 'Folder'),
    ('sfa-sfa-sfa-sendar-o', 'Sfa sfa sfa sendar'),
    ('keyboard-o', 'Keyboard'),
    ('bar-chart-o', 'Bar chart'),
    ('sort-asc', 'Sort asc'),
    ('archive', 'Archive'),
    ('eraser', 'Eraser'),
    ('inbox', 'Inbox'),
    ('truck', 'Truck'),
    ('phone-square', 'Phone square'),
    ('eye', 'Eye'),
    ('sun-o', 'Sun'),
    ('caret-down', 'Caret down'),
    ('bars', 'Bars'),
    ('won', 'Won'),
    ('frown-o', 'Frown'),
    ('repeat', 'Repeat'),
    ('arrow-circle-o-up', 'Arrow circleup'),
    ('question', 'Question'),
    ('meh-o', 'Meh'),
    ('terminal', 'Terminal'),
    ('caret-left', 'Caret left'),
    ('stop', 'Stop'),
    ('rss-square', 'Rss square'),
    ('files-o', 'Files'),
    ('pause', 'Pause'),
    ('mail-reply', 'Mail reply'),
    ('cutlery', 'Cutlery'),
    ('linux', 'Linux'),
    ('arrow-circle-left', 'Arrow circle left'),
    ('shopping-cart', 'Shopping cart'),
    ('unsortedfa-unsortedfaort-down', 'Unsortedfa unsortedfaort down'),
    ('exchange', 'Exchange'),
    ('angle-double-up', 'Angle double up'),
    ('forward', 'Forward'),
    ('cog', 'Cog'),
    ('arrow-circle-down', 'Arrow circle down'),
    ('tumblr-square', 'Tumblr square'),
    ('th', 'Th'),
    ('info', 'Info'),
    ('paste', 'Paste'),
    ('gavel', 'Gavel'),
    ('edi', 'Edi'),
    ('glass', 'Glass'),
    ('hand-o-right', 'Handright'),
    ('pinterest-square', 'Pinterest square'),
    ('lightbulb-o', 'Lightbulb'),
    ('caret-square-o-up', 'Caret squareup'),
    ('video-camera', 'Video camera'),
    ('long-arrow-left', 'Long arrow left'),
    ('caret-right', 'Caret right'),
    ('volume-down', 'Volume down'),
    ('clock-o', 'Clock'),
    ('arrow-up', 'Arrow up'),
    ('folder-open-o', 'Folder open'),
    ('angle-double-down', 'Angle double down'),
    ('facebook', 'Facebook'),
    ('twitter-square', 'Twitter square'),
    ('power-off', 'Power off'),
    ('user', 'User'),
    ('exclamation-circle', 'Exclamation circle'),
    ('level-down', 'Level down'),
    ('tint', 'Tint'),
    ('key', 'Key'),
    ('laptop', 'Laptop'),
    ('angle-double-left', 'Angle double left'),
    ('quote-left', 'Quote left'),
    ('circle-o', 'Circle'),
    ('mail-reply-all', 'Mail reply all'),
    ('group', 'Group'),
    ('microphone', 'Microphone'),
    ('camera-retro', 'Camera retro'),
    ('maxcdn', 'Maxcdn'),
    ('toggle-lef', 'Toggle lef'),
    ('play-circle-o', 'Play circle'),
    ('code-fork', 'Code fork'),
    ('try', 'Try'),
    ('quote-right', 'Quote right'),
    ('mobile', 'Mobile'),
    ('plus-circle', 'Plus circle'),
    ('folder-open', 'Folder open'),
    ('css3', 'Css3'),
    ('fast-forward', 'Fast forward'),
    ('toggle-down', 'Toggle down'),
    ('credit-card', 'Credit card'),
    ('caret-square-o-left', 'Caret squareleft'),
    ('angle-down', 'Angle down'),
    ('trello', 'Trello'),
    ('youtube-play', 'Youtube play'),
    ('arrow-left', 'Arrow left'),
    ('copy', 'Copy'),
    ('star-half-o', 'Star half'),
    ('chevron-up', 'Chevron up'),
    ('chevron-down', 'Chevron down'),
    ('check-circle-o', 'Check circle'),
    ('dashboard', 'Dashboard'),
    ('plus', 'Plus'),
    ('gamepad', 'Gamepad'),
    ('rub', 'Rub'),
    ('sign-in', 'Sign in'),
    ('sort-amount-desc', 'Sort amount desc'),
    ('bug', 'Bug'),
    ('medkit', 'Medkit'),
    ('cny', 'Cny'),
    ('arrows', 'Arrows'),
    ('map-marker', 'Map marker'),
    ('wheelchair', 'Wheelchair'),
    ('plus-square', 'Plus square'),
    ('male', 'Male'),
    ('envelope-o', 'Envelope'),
    ('xing-square', 'Xing square'),
    ('step-forward', 'Step forward'),
    ('pencil-square-o', 'Pencil square'),
    ('weibo', 'Weibo'),
    ('gear', 'Gear'),
    ('rocket', 'Rocket'),
    ('search-plus', 'Search plus'),
    ('bell', 'Bell'),
    ('undo', 'Undo'),
    ('fast-backward', 'Fast backward'),
    ('share-square', 'Share square'),
    ('asterisk', 'Asterisk'),
    ('arrow-down', 'Arrow down'),
    ('random', 'Random'),
    ('beer', 'Beer'),
    ('exclamation-triangle', 'Exclamation triangle'),
    ('volume-up', 'Volume up'),
    ('flag-checkered', 'Flag checkered'),
    ('ellipsis-h', 'Ellipsis h'),
    ('crop', 'Crop'),
    ('ellipsis-v', 'Ellipsis v'),
    ('gift', 'Gift'),
    ('strikethrough', 'Strikethrough'),
    ('reply-all', 'Reply all'),
    ('star-half', 'Star half'),
    ('download', 'Download'),
    ('chevron-circle-down', 'Chevron circle down'),
    ('hand-o-down', 'Handdown'),
    ('star-o', 'Star'),
    ('inr', 'Inr'),
    ('rupee', 'Rupee'),
    ('eur', 'Eur'),
    ('tumblr', 'Tumblr'),
    ('indent', 'Indent'),
    ('envelope', 'Envelope'),
    ('bitbucket-square', 'Bitbucket square'),
    ('legal', 'Legal'),
    ('gittip', 'Gittip'),
    ('chevron-left', 'Chevron left'),
    ('cogs', 'Cogs'),
    ('arrow-circle-o-left', 'Arrow circleleft'),
    ('briefcase', 'Briefcase'),
    ('user-md', 'User md'),
    ('angle-left', 'Angle left'),
    ('long-arrow-right', 'Long arrow right'),
    ('coffee', 'Coffee'),
    ('toggle-up', 'Toggle up'),
    ('youtube-square', 'Youtube square'),
    ('compress', 'Compress'),
    ('android', 'Android'),
    ('font', 'Font'),
    ('arrow-right', 'Arrow right'),
    ('minus', 'Minus'),
    ('bitbucket', 'Bitbucket'),
    ('headphones', 'Headphones'),
    ('paperclip', 'Paperclip'),
    ('rmb', 'Rmb'),
    ('minus-square', 'Minus square'),
    ('moon-o', 'Moon'),
    ('fighter-jet', 'Fighter jet'),
    ('sort-alpha-desc', 'Sort alpha desc'),
    ('star-half-empty', 'Star half empty'),
    ('share', 'Share'),
    ('comment', 'Comment'),
    ('stack-exchange', 'Stack exchange'),
    ('thumbs-up', 'Thumbs up'),
    ('chevron-circle-right', 'Chevron circle right'),
    ('adjust', 'Adjust'),
    ('signal', 'Signal'),
    ('sort-up', 'Sort up'),
    ('rotate-lef', 'Rotate lef'),
    ('save', 'Save'),
    ('eye-slash', 'Eye slash'),
    ('backward', 'Backward'),
    ('mail-forward', 'Mail forward'),
    ('link', 'Link'),
    ('table', 'Table'),
    ('tag', 'Tag'),
    ('turkish-lira', 'Turkish lira'),
    ('money', 'Money'),
    ('instagram', 'Instagram'),
    ('volume-off', 'Volume off'),
    ('unlock-alt', 'Unlock alt'),
    ('minus-circle', 'Minus circle'),
    ('adn', 'Adn'),
    ('list-ol', 'List ol'),
    ('magnet', 'Magnet'),
    ('linkedin', 'Linkedin'),
    ('reply', 'Reply'),
    ('smile-o', 'Smile'),
    ('twitter', 'Twitter'),
    ('expand', 'Expand'),
    ('flask', 'Flask'),
    ('flash', 'Flash'),
    ('trophy', 'Trophy'),
    ('long-arrow-down', 'Long arrow down'),
    ('angle-double-right', 'Angle double right'),
    ('home', 'Home'),
    ('bolt', 'Bolt'),
    ('italic', 'Italic'),
    ('comments', 'Comments'),
    ('file', 'File'),
    ('bold', 'Bold'),
    ('anchor', 'Anchor'),
    ('calendar', 'Calendar'),
    ('superscript', 'Superscript'),
    ('file-text-o', 'File text'),
    ('cloud', 'Cloud'),
    ('times', 'Times'),
    ('cu', 'Cu'),
    ('ambulance', 'Ambulance'),
    ('suitcase', 'Suitcase'),
    ('sort-alpha-asc', 'Sort alpha asc'),
    ('picture-o', 'Picture'),
    ('phone', 'Phone'),
    ('github-square', 'Github square'),
    ('windows', 'Windows'),
    ('tags', 'Tags'),
    ('text-height', 'Text height'),
    ('align-right', 'Align right'),
    ('angle-right', 'Angle right'),
    ('heart-o', 'Heart'),
    ('underline', 'Underline'),
    ('play-circle', 'Play circle'),
    ('plus-square-o', 'Plus square'),
    ('rss', 'Rss'),
    ('google-plus-square', 'Google plus square'),
    ('caret-square-o-right', 'Caret squareright'),
    ('rotate-righ', 'Rotate righ'),
    ('outdent', 'Outdent'),
    ('lock', 'Lock'),
    ('dot-circle-o', 'Dot circle'),
    ('clipboard', 'Clipboard'),
    ('github', 'Github'),
    ('jpy', 'Jpy'),
    ('vk', 'Vk'),
    ('print', 'Print'),
    ('code', 'Code'),
    ('book', 'Book'),
    ('pinterest', 'Pinterest'),
    ('youtube', 'Youtube'),
    ('deden', 'Deden'),
    ('fire', 'Fire'),
    ('tasks', 'Tasks'),
    ('xing', 'Xing'),
    ('play', 'Play'),
    ('flag-o', 'Flag'),
    ('search', 'Search'),
    ('renren', 'Renren'),
    ('toggle-righ', 'Toggle righ'),
    ('plane', 'Plane'),
    ('sort-numeric-desc', 'Sort numeric desc'),
    ('scissors', 'Scissors'),
    ('question-circle', 'Question circle'),
    ('crosshairs', 'Crosshairs'),
    ('apple', 'Apple'),
    ('wrench', 'Wrench'),
    ('sitemap', 'Sitemap'),
    ('file-o', 'File'),
    ('krw', 'Krw'),
    ('floppy-o', 'Floppy'),
    ('upload', 'Upload'),
    ('arrow-circle-o-right', 'Arrow circleright'),
    ('info-circle', 'Info circle'),
    ('cloud-upload', 'Cloud upload'),
    ('search-minus', 'Search minus'),
    ('music', 'Music'),
    ('star-half-full', 'Star half full'),
    ('mobile-phone', 'Mobile phone'),
    ('dollar', 'Dollar'),
    ('sort-amount-asc', 'Sort amount asc'),
    ('hdd-o', 'Hdd'),
    ('bullseye', 'Bullseye'),
    ('location-arrow', 'Location arrow'),
    ('female', 'Female'),
    ('thumb-tack', 'Thumb tack'),
    ('align-justify', 'Align justify'),
    ('external-link', 'External link'),
    ('arrow-circle-right', 'Arrow circle right'),
    ('level-up', 'Level up'),
    ('gears', 'Gears'),
    ('foursquare', 'Foursquare'),
    ('exclamation', 'Exclamation'),
    ('star', 'Star'),
    ('google-plus', 'Google plus'),
    ('h-square', 'H square'),
    ('unlock', 'Unlock'),
    ('sort-desc', 'Sort desc'),
    ('thumbs-down', 'Thumbs down'),
    ('eject', 'Eject'),
    ('linkedin-square', 'Linkedin square'),
    ('pagelines', 'Pagelines'),
    ('check', 'Check'),
    ('compass', 'Compass'),
    ('angle-up', 'Angle up'),
    ('qrcode', 'Qrcode'),
    ('bookmark-o', 'Bookmark'),
    ('usd', 'Usd'),
    ('chevron-right', 'Chevron right'),
    ('ruble', 'Ruble'),
    ('btc', 'Btc'),
    ('lemon-o', 'Lemon'),
    ('arrow-circle-up', 'Arrow circle up'),
    ('comments-o', 'Comments'),
    ('check-square-o', 'Check square'),
    ('tablet', 'Tablet'),
    ('chain-broken', 'Chain broken'),
    ('puzzle-piece', 'Puzzle piece'),
    ('spinner', 'Spinner'),
    ('globe', 'Globe'),
    ('vimeo-square', 'Vimeo square'),
    ('magic', 'Magic'),
    ('align-center', 'Align center'),
    ('warning', 'Warning'),
    ('desktop', 'Desktop'),
    ('thumbs-o-up', 'Thumbsup'),
    ('dribbble', 'Dribbble'),
    ('square-o', 'Square'),
    ('columns', 'Columns'),
    ('flickr', 'Flickr'),
    ('retweet', 'Retweet'),
    ('flag', 'Flag'),
    ('bitcoin', 'Bitcoin'),
    ('text-width', 'Text width'),
    ('arrows-v', 'Arrows v'),
    ('hospital-o', 'Hospital'),
    ('step-backward', 'Step backward'),
    ('bullhorn', 'Bullhorn'),
    ('fire-extinguisher', 'Fire extinguisher'),
    ('arrows-h', 'Arrows h'),
    ('refresh', 'Refresh'),
    ('github-alt', 'Github alt'),
    ('chain', 'Chain'),
    ('facebook-square', 'Facebook square'),
    ('rouble', 'Rouble'),
    ('minus-square-o', 'Minus square')
)