ICONS = (
	('adjust', 'Adjust'),
	('adn', 'App.net'),
	('apple', 'Apple'),
	('anchor', 'Anchor'),
	('android', 'Android'),
	('align-center', 'Align center'),
	('align-justify', 'Align justify'),
	('align-left', 'Align left'),
	('align-right', 'Align right'),
	('ambulance', 'Ambulance'),
	('angle-down', 'Angle down'),
	('angle-left', 'Angle left'),
	('angle-right', 'Angle right'),
	('angle-up', 'Angle up'),
	('archive', 'Archive'),
	('arrow-down', 'Arrow down'),
	('arrow-left', 'Arrow left'),
	('arrow-right', 'Arrow right'),
	('arrow-up', 'Arrow up'),
	('asterisk', 'Asterisk'),
	('backward', 'Backward'),
	('ban-circle', 'Ban (circle)'),
	('bar-chart', 'Bar chart'),
	('barcode', 'Barcode'),
	('beaker', 'Beaker'),
	('beer', 'Beer'),
	('bell', 'Bell'),
	('bell-alt', 'Bell (alt)'),
	('bitbucket', 'BitBucket'),
	('bitbucket-sign', 'BitBucket sign'),
	('bold', 'Bold'),
	('bolt', 'Bolt'),
	('book', 'Book'),
	('bookmark', 'Bookmark'),
	('bookmark-empty', 'Bookmark, empty'),
	('briefcase', 'Briefcase'),
	('btc', 'Bitcoin'),
	('bug', 'Bug'),
	('building', 'Building'),
	('bullhorn', 'Bullhorn'),
	('bullseye', 'Bullseye'),
	('calendar', 'Calendar'),
	('calendar-empty', 'calendar (empty)'),
	('camera', 'Camera'),
	('camera-retro', 'Camera (retro)'),
	('caret-down', 'Caret, down'),
	('caret-left', 'Caret, left'),
	('caret-right', 'Caret, right'),
	('caret-up', 'Caret, up'),
	('certificate', 'Certificate'),
	('check', 'Check'),
	('check-empty', 'Check, empty'),
	('check-minus', 'Check, minus'),
	('check-sign', 'Check sign'),
	('chevron-down', 'Chevron, down'),
	('chevron-left', 'Chevron, left'),
	('chevron-right', 'Chevron, right'),
	('chevron-up', 'Chevron, up'),
	('chevron-sign-down', 'Chevron sign, down'),
	('chevron-sign-left', 'Chevron sign, left'),
	('chevron-sign-right', 'Chevron sign, right'),
	('chevron-sign-up', 'Chevron sign, up'),
	('circle', 'Circle'),
	('circle-arrow-down', 'Circle with arrow down'),
	('circle-arrow-left', 'Circle with arrow left'),
	('circle-arrow-right', 'Circle with arrow right'),
	('circle-arrow-up', 'Circle with arrow up'),
	('circle-blank', 'Circle, blank'),
	('cloud', 'Cloud'),
	('cloud-download', 'Cloud download'),
	('cloud-upload', 'Cloud upload'),
	('cny', 'Chinese Yuan Renminbi'),
	('code', 'Code'),
	('code-fork', 'Code, fork'),
	('coffee', 'Coffee'),
	('cog', 'Cog'),
	('cogs', 'Cogs'),
	('collapse', 'Collapse'),
	('collapse-top', 'Collapse top'),
	('collapse-alt', 'Collapse (alt)'),
	('columns', 'Columns'),
	('comment', 'Comment'),
	('comment-alt', 'Comment (alt)'),
	('comments', 'Comments'),
	('comments-alt', 'Comments (alt)'),
	('compass', 'Compass'),
	('copy', 'Copy'),
	('credit-card', 'Credit card'),
	('crop', 'Crop'),
	('css3', 'CSS3'),
	('cut', 'Cut'),
	('dashboard', 'Dashboard'),
	('desktop', 'Desktop'),
	('double-angle-down', 'Double angle down'),
	('double-angle-left', 'Double angle left'),
	('double-angle-right', 'Double angle right'),
	('double-angle-up', 'Double angle up'),
	('download', 'Download'),
	('download-alt', 'Download (alt)'),
	('dribbble', 'Dribbble'),
	('dropbox', 'DropBox'),
	('edit', 'Edit'),
	('edit-sign', 'Edit sign'),
	('eject', 'Eject'),
	('ellipsis-horizontal', 'Ellipsis, horizontal'),
	('ellipsis-vertical', 'Ellipsis, vertical'),
	('envelope', 'Envelope'),
	('envelope-alt', 'Envelope (alt)'),
	('eraser', 'Eraser'),
	('euro', 'Euro'),
	('exchange', 'Exchange'),
	('exclamation', 'Exclamation'),
	('exclamation-sign', 'Exclamation sign'),
	('expand', 'Expand'),
	('expand-alt', 'Expand (alt)'),
	('external-link', 'External link'),
	('external-link-sign', 'External link sign'),
	('eye-close', 'Eye close'),
	('eye-open', 'Eye open'),
	('facebook', 'Facebook'),
	('facebook-sign', 'Facebook sign'),
	('facetime-video', 'FaceTime video'),
	('fast-backward', 'Fast backward'),
	('fast-forward', 'Fast forward'),
	('female', 'Female'),
	('fighter-jet', 'Fighter jet'),
	('file', 'File'),
	('file-alt', 'File (alt)'),
	('film', 'Film'),
	('filter', 'Filter'),
	('fire', 'Fire'),
	('fire-extinguisher', 'Fire extinguisher'),
	('flag', 'Flag'),
	('flag-alt', 'Flag (alt)'),
	('flag-checkered', 'Flag, checkered'),
	('flickr', 'Flickr'),
	('folder-close', 'Folder close'),
	('folder-close-alt', 'Folder close (alt)'),
	('folder-open', 'Folder open'),
	('folder-open-alt', 'Folder open (alt)'),
	('font', 'Font'),
	('food', 'Food'),
	('forward', 'Forward'),
	('frown', 'Frown'),
	('foursquare', 'Foursquare'),
	('fullscreen', 'Fullscreen'),
	('gamepad', 'Gamepad'),
	('gbp', 'Great British Pound'),
	('gift', 'Gift'),
	('github', 'GitHub'),
	('github-alt', 'GitHub (alt)'),
	('github-sign', 'GitHub sign'),
	('gittip', 'GiTtip'),
	('glass', 'Glass'),
	('globe', 'Globe'),
	('google-plus', 'Google+'),
	('google-plus-sign', 'Google+ sign'),
	('group', 'Group'),
	('h-sign', 'H sign'),
	('hand-down', 'Hand down'),
	('hand-left', 'Hand left'),
	('hand-right', 'Hand right'),
	('hand-up', 'Hand up'),
	('hdd', 'Hard disk drive'),
	('headphones', 'Headphones'),
	('heart', 'Heart'),
	('heart-empty', 'Heart, empty'),
	('home', 'Home'),
	('hospital', 'Hospital'),
	('html5', 'HTML5'),
	('inbox', 'Inbox'),
	('indent-left', 'Indent left'),
	('indent-right', 'Indent right'),
	('info', 'Info'),
	('info-sign', 'Info sign'),
	('inr', 'Indian Rupee'),
	('instagram', 'Instagram'),
	('italic', 'Italic'),
	('jpy', 'Japanese Yen'),
	('key', 'Key'),
	('keyboard', 'Keyboard'),
	('krw', 'South Korean Won'),
	('laptop', 'Laptop'),
	('leaf', 'Leaf'),
	('legal', 'Legal'),
	('lemon', 'Lemon'),
	('level-down', 'Level down'),
	('level-up', 'Level up'),
	('lightbulb', 'Lightbulb'),
	('link', 'Link'),
	('linkedin', 'LinkedIn'),
	('linkedin-sign', 'LinkedIn sign'),
	('linux', 'Linux'),
	('list', 'List'),
	('list-alt', 'List (alt)'),
	('list-ol', 'List, ordered'),
	('list-ul', 'List, unordered'),
	('location-arrow', 'Location arrow'),
	('lock', 'Lock'),
	('long-arrow-down', 'Long arrow down'),
	('long-arrow-up', 'Long arrow up'),
	('long-arrow-left', 'Long arrow left'),
	('long-arrow-right', 'Long arrow right'),
	('mail-forward', 'Mail forward'),
	('mail-reply', 'Mail reply'),
	('mail-reply-alt', 'Mail reply (alt)'),
	('magic', 'Magic'),
	('magnet', 'Magnet'),
	('male', 'Male'),
	('map-marker', 'Map marker'),
	('maxcdn', 'MaxCDN'),
	('medkit', 'Medkit'),
	('meh', 'Meh'),
	('microphone', 'Microphone'),
	('microphone-off', 'Microphone, off'),
	('minus', 'Minus'),
	('minus-sign', 'Minus sign'),
	('minus-sign-alt', 'Minus sign (alt)'),
	('mobile-phone', 'Mobile phone'),
	('money', 'Money'),
	('moon', 'Moon'),
	('move', 'Move'),
	('music', 'Music'),
	('off', 'Off'),
	('ok', 'OK'),
	('ok-circle', 'OK (circle)'),
	('ok-sign', 'OK sign'),
	('paper-clip', 'Paper clip'),
	('paste', 'Paste'),
	('pause', 'Pause'),
	('pencil', 'Pencil'),
	('phone', 'Phone'),
	('phone-sign', 'Phone sign'),
	('picture', 'Picture'),
	('pinterest', 'Pinterest'),
	('pinterest-sign', 'Pinterest sign'),
	('plane', 'Plane'),
	('play', 'Play'),
	('play-circle', 'Play (circle)'),
	('play-sign', 'Play sign'),
	('plus', 'Plus'),
	('plus-sign', 'Plus sign'),
	('plus-sign-alt', 'Plus sign (alt)'),
	('print', 'Print'),
	('pushpin', 'Pushpin'),
	('puzzle-piece', 'Puzzle piece'),
	('qrcode', 'QR code'),
	('question', 'Question'),
	('question-sign', 'Question sign'),
	('quote-left', 'Quote, left'),
	('quote-right', 'Quote, right'),
	('random', 'Random'),
	('refresh', 'Refresh'),
	('remove', 'Remove'),
	('remove-circle', 'Remove (circle)'),
	('remove-sign', 'Remove sign'),
	('reorder', 'Reorder'),
	('repeat', 'Repeat'),
	('reply', 'Reply'),
	('reply-alt', 'Reply (alt)'),
	('resize-full', 'Resize, full'),
	('resize-horizontal', 'Resize horizontal'),
	('resize-small', 'Resize, small'),
	('resize-vertical', 'Resize vertical'),
	('retweet', 'Retweet'),
	('road', 'Road'),
	('rocket', 'Rocket'),
	('rotate-left', 'Rotate left'),
	('rotate-right', 'Rotate right'),
	('rss', 'RSS'),
	('rss-sign', 'RSS sign'),
	('save', 'Save'),
	('screenshot', 'Screenshot'),
	('search', 'Search'),
	('share', 'Share'),
	('share-alt', 'Share (alt)'),
	('share-sign', 'Share sign'),
	('shield', 'Shield'),
	('shopping-cart', 'Shopping cart'),
	('sign-blank', 'Sign, blank'),
	('signin', 'Sign in'),
	('signal', 'Signal'),
	('signout', 'Signout'),
	('sitemap', 'Sitemap'),
	('skype', 'Skype'),
	('smile', 'Smile'),
	('sort', 'Sort'),
	('sort-by-alphabet', 'Sort by alphabet'),
	('sort-by-alphabet-alt', 'Sort by alphabet (alt)'),
	('sort-by-attributes', 'Sort by attributes'),
	('sort-by-attributes-alt', 'Sort byattributes (alt)'),
	('sort-by-order', 'Sort by order'),
	('sort-by-order-alt', 'Sort by order (alt)'),
	('sort-down', 'Sort down'),
	('sort-up', 'Sort up'),
	('spinner', 'Spinner'),
	('stackexchange', 'StackExchange'),
	('star', 'Star'),
	('star-empty', 'Star, empty'),
	('star-half', 'Star, half'),
	('step-backward', 'Step backward'),
	('step-forward', 'Step forward'),
	('star-half-empty', 'Star, half-empty'),
	('star-half-full', 'Star, half-full'),
	('stethoscope', 'Stethoscope'),
	('stop', 'Stop'),
	('strikethrough', 'Strikethrough'),
	('subscript', 'Subscript'),
	('suitcase', 'Suitcase'),
	('sun', 'Sun'),
	('superscript', 'Superscript'),
	('table', 'Table'),
	('tablet', 'Tablet'),
	('tag', 'Tag'),
	('tags', 'Tags'),
	('tasks', 'Tasks'),
	('terminal', 'Terminal'),
	('text-height', 'Text height'),
	('text-width', 'Text width'),
	('th', 'TH'),
	('th-large', 'TH, large'),
	('th-list', 'TH list'),
	('thumbs-down', 'Thumbs down'),
	('thumbs-up', 'Thumbs up'),
	('ticket', 'Ticket'),
	('time', 'Time'),
	('tint', 'Tint'),
	('trash', 'Trash'),
	('trello', 'Trello'),
	('trophy', 'Trophy'),
	('truck', 'Truck'),
	('tumblr', 'Tumblr'),
	('tumblr-sign', 'Tumblr sign'),
	('twitter', 'Twitter'),
	('twitter-sign', 'Twitter sign'),
	('umbrella', 'Umbrella'),
	('underline', 'Underline'),
	('undo', 'Undo'),
	('unlink', 'Unlink'),
	('unlock', 'Unlock'),
	('unlock-alt', 'Unlock (alt)'),
	('upload', 'Upload'),
	('upload-alt', 'Upload (alt)'),
	('usd', 'United States Dollar'),
	('user', 'User'),
	('user-md', 'User MD'),
	('vk', 'VK'),
	('volume-down', 'Volume down'),
	('volume-off', 'Volume off'),
	('volume-up', 'Volume up'),
	('warning-sign', 'Warning sign'),
	('weibo', 'Weibo'),
	('windows', 'Windows'),
	('wrench', 'Wrench'),
	('xing', 'Xing'),
	('xing-sign', 'Xing sign'),
	('youtube-play', 'YouTube play'),
	('youtube-sign', 'YouTube sign'),
	('youtube', 'YouTube'),
	('zoom-in', 'Zoom in'),
	('zoom-out', 'Zoom out')
)